apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-playing-craps
  
  labels:
    app: bots-playing-craps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bots-playing-craps
  template:
    metadata:
      labels:
        app: bots-playing-craps
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: bots-playing-craps
          image: ghcr.io/unkhz/bots-playing-craps:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"  
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 300
            timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: bots-playing-craps-service
  
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bots-playing-craps.khz.fi
spec:
  selector:
    app: bots-playing-craps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bots-playing-craps-ingress
  
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: bots-playing-craps.khz.fi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bots-playing-craps-service
                port:
                  number: 80
  tls:
    - hosts:
        - bots-playing-craps.khz.fi
      secretName: bots-playing-craps-tls
