apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
images:
  - name: ghcr.io/unkhz/bots-playing-craps:latest
    newTag: 704f066054941d2981d289a75c7850a8f54ab1d0
